create table if not exists contract_templates (
  id int unsigned auto_increment primary key,
  company_id int unsigned not null,
  title varchar(160) not null,
  body longtext not null,
  source_file_original varchar(255) null,
  source_file_stored varchar(255) null,
  source_file_size int unsigned null,
  source_file_mime varchar(100) null,
  active tinyint(1) not null default 1,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp null default null on update current_timestamp,
  constraint contract_templates_company_fk foreign key (company_id) references companies(id) on delete cascade,
  index ct_company_idx (company_id, active)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table if not exists project_contracts (
  id int unsigned auto_increment primary key,
  company_id int unsigned not null,
  client_project_id int unsigned not null,
  template_id int unsigned null,
  title varchar(180) not null,
  body longtext not null,
  source_file_original varchar(255) null,
  source_file_stored varchar(255) null,
  source_file_size int unsigned null,
  source_file_mime varchar(100) null,
  status enum('DRAFT','SENT','ACCEPTED','SIGNED_GOVBR','SIGNED_MANUAL','CANCELED') not null default 'DRAFT',
  signature_method enum('PENDING','INTERNAL_ACCEPTANCE','GOVBR_UPLOAD','MANUAL_DRAW') not null default 'PENDING',
  public_token varchar(64) not null unique,
  accepted_name varchar(160) null,
  accepted_document varchar(40) null,
  accepted_email varchar(160) null,
  accepted_ip varchar(80) null,
  accepted_user_agent varchar(255) null,
  accepted_at datetime null,
  manual_signature_data longtext null,
  signed_file_original varchar(255) null,
  signed_file_stored varchar(255) null,
  signed_file_size int unsigned null,
  signed_file_mime varchar(100) null,
  signed_file_uploaded_at datetime null,
  created_by_user_id int unsigned null,
  created_at timestamp not null default current_timestamp,
  updated_at timestamp null default null on update current_timestamp,
  constraint project_contracts_company_fk foreign key (company_id) references companies(id) on delete cascade,
  constraint project_contracts_project_fk foreign key (client_project_id) references client_projects(id) on delete cascade,
  constraint project_contracts_template_fk foreign key (template_id) references contract_templates(id) on delete set null,
  constraint project_contracts_user_fk foreign key (created_by_user_id) references users(id) on delete set null,
  index pc_company_status_idx (company_id, status),
  index pc_project_idx (client_project_id)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;
